import { type Product } from "./types";

export const data: Product[] = [
  {
    id: "1",
    name: "Pipedrive",
    slug: "pipedrive-crm",
    logoUrl: "https://picsum.photos/seed/pipedrive/40",
    productScoring: {
      stackfixScore: 8,
      fitScore: 87,
    },
    dealBreakers: ["Poor customer support"],
    pricing: {
      totalPrice: 1890.99,
      period: "month",
    },
    requirements: [
      { name: "Store contact or deal information", status: "met" },
      { name: "Email warm up", status: "unmet" },
      { name: "Email sequencing", status: "met" },
      { name: "Email templates", status: "partially-met" },
      { name: "Geo-fencing lead management", status: "unmet" },
      { name: "Track website activity of new vistors", status: "met" },
    ],
  },
  {
    id: "2",
    name: "Salesforce",
    slug: "salesforce-crm",
    logoUrl: "https://picsum.photos/seed/salesforce/40",
    productScoring: {
      stackfixScore: 5,
      fitScore: 75,
    },
    dealBreakers: ["Complex UX"],
    pricing: {
      totalPrice: 3567.99,
      period: "month",
    },
    requirements: [
      { name: "Store contact or deal information", status: "met" },
      { name: "Email warm up", status: "met" },
      { name: "Email sequencing", status: "met" },
      { name: "Email templates", status: "met" },
      { name: "Geo-fencing lead management", status: "met" },
      { name: "Track website activity of new vistors", status: "unmet" },
    ],
  },
  {
    id: "3",
    name: "HubSpot",
    slug: "hubspot-crm",
    logoUrl: "https://picsum.photos/seed/hubspot/40",
    productScoring: {
      stackfixScore: 9,
      fitScore: 92,
    },
    dealBreakers: ["High price point", "Limited API access"],
    pricing: {
      totalPrice: 2450.0,
      period: "month",
    },
    requirements: [
      { name: "Store contact or deal information", status: "met" },
      { name: "Email warm up", status: "met" },
      { name: "Email sequencing", status: "met" },
      { name: "Email templates", status: "met" },
      { name: "Geo-fencing lead management", status: "partially-met" },
      { name: "Track website activity of new vistors", status: "met" },
    ],
  },
  {
    id: "4",
    name: "Zoho CRM",
    slug: "zoho-crm",
    logoUrl: "https://picsum.photos/seed/zoho/40",
    productScoring: {
      stackfixScore: 7,
      fitScore: 83,
    },
    dealBreakers: ["Limited integration options"],
    pricing: {
      totalPrice: 899.99,
      period: "month",
    },
    requirements: [
      { name: "Store contact or deal information", status: "met" },
      { name: "Email warm up", status: "partially-met" },
      { name: "Email sequencing", status: "met" },
      { name: "Email templates", status: "met" },
      { name: "Geo-fencing lead management", status: "unmet" },
      {
        name: "Track website activity of new vistors",
        status: "partially-met",
      },
    ],
  },
  {
    id: "5",
    name: "Monday.com Sales CRM",
    slug: "monday-sales-crm",
    logoUrl: "https://picsum.photos/seed/monday/40",
    productScoring: {
      stackfixScore: 8,
      fitScore: 85,
    },
    dealBreakers: ["Steep learning curve"],
    pricing: {
      totalPrice: 1299.0,
      period: "month",
    },
    requirements: [
      { name: "Store contact or deal information", status: "met" },
      { name: "Email warm up", status: "unmet" },
      { name: "Email sequencing", status: "partially-met" },
      { name: "Email templates", status: "met" },
      { name: "Geo-fencing lead management", status: "partially-met" },
      { name: "Track website activity of new vistors", status: "met" },
    ],
  },
  {
    id: "6",
    name: "Fresh Sales",
    slug: "fresh-sales-crm",
    logoUrl: "https://picsum.photos/seed/freshsales/40",
    productScoring: {
      stackfixScore: 6,
      fitScore: 78,
    },
    dealBreakers: ["Limited customization options", "Basic reporting"],
    pricing: {
      totalPrice: 599.99,
      period: "month",
    },
    requirements: [
      { name: "Store contact or deal information", status: "met" },
      { name: "Email warm up", status: "unmet" },
      { name: "Email sequencing", status: "partially-met" },
      { name: "Email templates", status: "met" },
      { name: "Geo-fencing lead management", status: "unmet" },
      {
        name: "Track website activity of new vistors",
        status: "partially-met",
      },
    ],
  },
  {
    id: "7",
    name: "Copper CRM",
    slug: "copper-crm",
    logoUrl: "https://picsum.photos/seed/copper/40",
    productScoring: {
      stackfixScore: 7,
      fitScore: 81,
    },
    dealBreakers: ["Limited third-party integrations"],
    pricing: {
      totalPrice: 1199.0,
      period: "month",
    },
    requirements: [
      { name: "Store contact or deal information", status: "met" },
      { name: "Email warm up", status: "partially-met" },
      { name: "Email sequencing", status: "met" },
      { name: "Email templates", status: "met" },
      { name: "Geo-fencing lead management", status: "unmet" },
      { name: "Track website activity of new vistors", status: "met" },
    ],
  },
  {
    id: "8",
    name: "Insightly",
    slug: "insightly-crm",
    logoUrl: "https://picsum.photos/seed/insightly/40",
    productScoring: {
      stackfixScore: 3,
      fitScore: 45,
    },
    dealBreakers: ["Limited mobile functionality", "Basic automation features"],
    pricing: {
      totalPrice: 799.0,
      period: "month",
    },
    requirements: [
      { name: "Store contact or deal information", status: "met" },
      { name: "Email warm up", status: "unmet" },
      { name: "Email sequencing", status: "partially-met" },
      { name: "Email templates", status: "met" },
      { name: "Geo-fencing lead management", status: "unmet" },
      {
        name: "Track website activity of new vistors",
        status: "partially-met",
      },
    ],
  },
  {
    id: "9",
    name: "Keap",
    slug: "keap-crm",
    logoUrl: "https://picsum.photos/seed/keap/40",
    productScoring: {
      stackfixScore: 9,
      fitScore: 95,
    },
    dealBreakers: ["Expensive add-ons"],
    pricing: {
      totalPrice: 1599.99,
      period: "month",
    },
    requirements: [
      { name: "Store contact or deal information", status: "met" },
      { name: "Email warm up", status: "met" },
      { name: "Email sequencing", status: "met" },
      { name: "Email templates", status: "met" },
      { name: "Geo-fencing lead management", status: "met" },
      { name: "Track website activity of new vistors", status: "met" },
    ],
  },
  {
    id: "10",
    name: "Really Simple CRM",
    slug: "really-simple-crm",
    logoUrl: "https://picsum.photos/seed/reallysimple/40",
    productScoring: {
      stackfixScore: 4,
      fitScore: 62,
    },
    dealBreakers: ["Limited advanced features", "No customer support"],
    pricing: {
      totalPrice: 0,
      period: "month",
    },
    requirements: [
      { name: "Store contact or deal information", status: "met" },
      { name: "Email warm up", status: "unmet" },
      { name: "Email sequencing", status: "unmet" },
      { name: "Email templates", status: "partially-met" },
      { name: "Geo-fencing lead management", status: "unmet" },
      { name: "Track website activity of new vistors", status: "unmet" },
    ],
  },
  {
    id: "11",
    name: "Nimble",
    slug: "nimble-crm",
    logoUrl: "https://picsum.photos/seed/nimble/40",
    productScoring: {
      stackfixScore: 2,
      fitScore: 35,
    },
    dealBreakers: [
      "Limited reporting capabilities",
      "Poor performance",
      "Outdated UI",
    ],
    pricing: {
      totalPrice: 399.99,
      period: "month",
    },
    requirements: [
      { name: "Store contact or deal information", status: "partially-met" },
      { name: "Email warm up", status: "unmet" },
      { name: "Email sequencing", status: "unmet" },
      { name: "Email templates", status: "partially-met" },
      { name: "Geo-fencing lead management", status: "unmet" },
      {
        name: "Track website activity of new vistors",
        status: "partially-met",
      },
    ],
  },
  {
    id: "12",
    name: "OpenCRM",
    slug: "open-crm",
    logoUrl: "https://picsum.photos/seed/opencrm/40",
    productScoring: {
      stackfixScore: 5,
      fitScore: 71,
    },
    dealBreakers: ["Self-hosted only", "Technical setup required"],
    pricing: {
      totalPrice: 0,
      period: "month",
    },
    requirements: [
      { name: "Store contact or deal information", status: "met" },
      { name: "Email warm up", status: "partially-met" },
      { name: "Email sequencing", status: "partially-met" },
      { name: "Email templates", status: "met" },
      { name: "Geo-fencing lead management", status: "unmet" },
      {
        name: "Track website activity of new vistors",
        status: "partially-met",
      },
    ],
  },
  {
    id: "13",
    name: "Nutshell Pro",
    slug: "nutshell-pro-crm",
    logoUrl: "https://picsum.photos/seed/nutshell/40",
    productScoring: {
      stackfixScore: 9,
      fitScore: 98,
    },
    dealBreakers: [],
    pricing: {
      totalPrice: 499.99,
      period: "month",
    },
    requirements: [
      { name: "Store contact or deal information", status: "met" },
      { name: "Email warm up", status: "met" },
      { name: "Email sequencing", status: "met" },
      { name: "Email templates", status: "met" },
      { name: "Geo-fencing lead management", status: "met" },
      { name: "Track website activity of new vistors", status: "met" },
    ],
  },
  {
    id: "14",
    name: "Vtiger Community",
    slug: "vtiger-community-crm",
    logoUrl: "https://picsum.photos/seed/vtiger/40",
    productScoring: {
      stackfixScore: 6,
      fitScore: 68,
    },
    dealBreakers: [
      "Complex setup process",
      "Limited features",
      "Community support only",
    ],
    pricing: {
      totalPrice: 0,
      period: "month",
    },
    requirements: [
      { name: "Store contact or deal information", status: "met" },
      { name: "Email warm up", status: "unmet" },
      { name: "Email sequencing", status: "partially-met" },
      { name: "Email templates", status: "met" },
      { name: "Geo-fencing lead management", status: "unmet" },
      {
        name: "Track website activity of new vistors",
        status: "partially-met",
      },
    ],
  },
  {
    id: "15",
    name: "SugarCRM Enterprise",
    slug: "sugar-crm-enterprise",
    logoUrl: "https://picsum.photos/seed/sugarcrm/40",
    productScoring: {
      stackfixScore: 10,
      fitScore: 99,
    },
    dealBreakers: ["Enterprise pricing"],
    pricing: {
      totalPrice: 4799.99,
      period: "month",
    },
    requirements: [
      { name: "Store contact or deal information", status: "met" },
      { name: "Email warm up", status: "met" },
      { name: "Email sequencing", status: "met" },
      { name: "Email templates", status: "met" },
      { name: "Geo-fencing lead management", status: "met" },
      { name: "Track website activity of new vistors", status: "met" },
    ],
  },
  {
    id: "16",
    name: "Bitrix24 Free",
    slug: "bitrix24-free-crm",
    logoUrl: "https://picsum.photos/seed/bitrix24/40",
    productScoring: {
      stackfixScore: 7,
      fitScore: 81,
    },
    dealBreakers: ["Limited users", "Basic features only"],
    pricing: {
      totalPrice: 0,
      period: "month",
    },
    requirements: [
      { name: "Store contact or deal information", status: "met" },
      { name: "Email warm up", status: "unmet" },
      { name: "Email sequencing", status: "partially-met" },
      { name: "Email templates", status: "met" },
      { name: "Geo-fencing lead management", status: "unmet" },
      {
        name: "Track website activity of new vistors",
        status: "partially-met",
      },
    ],
  },
  {
    id: "17",
    name: "Agile CRM",
    slug: "agile-crm",
    logoUrl: "https://picsum.photos/seed/agilecrm/40",
    productScoring: {
      stackfixScore: 1,
      fitScore: 25,
    },
    dealBreakers: [
      "Unreliable service",
      "Poor support",
      "Buggy interface",
      "Limited features",
    ],
    pricing: {
      totalPrice: 599.99,
      period: "month",
    },
    requirements: [
      { name: "Store contact or deal information", status: "partially-met" },
      { name: "Email warm up", status: "unmet" },
      { name: "Email sequencing", status: "unmet" },
      { name: "Email templates", status: "partially-met" },
      { name: "Geo-fencing lead management", status: "unmet" },
      { name: "Track website activity of new vistors", status: "unmet" },
    ],
  },
];
